### ISSUE TITLE
Houston, we haz probz

### ISSUE THREAD

**Issue by anulettingitbe** [pramodsum/Cooking-In-Pajamas#11]
I don't know what to call this issue, but something is clearly wrong here: 
http://serene-scrubland-8972.herokuapp.com/pardon-my-french/

**Comment by pramodsum** [comment]
Where did you click on that link from? It should be http://serene-scrubland-8972.herokuapp.com/pardon-my-french/

**Comment by anulettingitbe** [comment]
I navigated there from the main page - was just creeping about!

**Comment by pramodsum** [comment]
No idea what happened here... will reopen if it pops up again
